services:
  taskeasyapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: 'taskeasy'
      POSTGRES_PASSWORD: 'senha123'
      POSTGRES_USER: 'victor'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
